server:
  port: 8081

spring:
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@m220-mflix.xfd1g.mongodb.net/${MONGO_DB_NAME}?retryWrites=true&w=majority
      uuid-representation: STANDARD

kafka:
  bootstrap:
    servers: pkc-2396y.us-east-1.aws.confluent.cloud:9092
  consumer:
    mercadoria:
      topic: mercadoria.topic
  properties:
    security-protocol: SASL_SSL
    sasl-mechanism: PLAIN
    client-dns-lookup: use_all_dns_ips
    sasl-jaas-config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='${KAFKA_SASL_USERNAME}'   password='${KAFKA_SASL_PASSWORD}';
    session-timeout-ms: 45000

management:
  metrics:
    use-global-registry: false
    enable:
      jvm:
        gc: false
        buffer: false
        classes: false
        threads: false
        memory: false
      logback: false
      mongodb: false
      disk: false
      process: false
      executor: false
      system:
        cpu: false
        load: false
      application: false
      spring:
        kafka: false
      http: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus